// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: athyr.proto

package athyrv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Athyr_Connect_FullMethodName        = "/athyr.v1.Athyr/Connect"
	Athyr_Heartbeat_FullMethodName      = "/athyr.v1.Athyr/Heartbeat"
	Athyr_Disconnect_FullMethodName     = "/athyr.v1.Athyr/Disconnect"
	Athyr_Publish_FullMethodName        = "/athyr.v1.Athyr/Publish"
	Athyr_Subscribe_FullMethodName      = "/athyr.v1.Athyr/Subscribe"
	Athyr_Request_FullMethodName        = "/athyr.v1.Athyr/Request"
	Athyr_Complete_FullMethodName       = "/athyr.v1.Athyr/Complete"
	Athyr_CompleteStream_FullMethodName = "/athyr.v1.Athyr/CompleteStream"
	Athyr_ResumeStream_FullMethodName   = "/athyr.v1.Athyr/ResumeStream"
	Athyr_ListModels_FullMethodName     = "/athyr.v1.Athyr/ListModels"
	Athyr_CreateSession_FullMethodName  = "/athyr.v1.Athyr/CreateSession"
	Athyr_GetSession_FullMethodName     = "/athyr.v1.Athyr/GetSession"
	Athyr_DeleteSession_FullMethodName  = "/athyr.v1.Athyr/DeleteSession"
	Athyr_AddHint_FullMethodName        = "/athyr.v1.Athyr/AddHint"
	Athyr_ListAgents_FullMethodName     = "/athyr.v1.Athyr/ListAgents"
	Athyr_GetAgent_FullMethodName       = "/athyr.v1.Athyr/GetAgent"
	Athyr_KVGet_FullMethodName          = "/athyr.v1.Athyr/KVGet"
	Athyr_KVPut_FullMethodName          = "/athyr.v1.Athyr/KVPut"
	Athyr_KVDelete_FullMethodName       = "/athyr.v1.Athyr/KVDelete"
	Athyr_KVList_FullMethodName         = "/athyr.v1.Athyr/KVList"
)

// AthyrClient is the client API for Athyr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Athyr is the main platform service that agents interact with.
type AthyrClient interface {
	// Connect registers an agent with the platform.
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	// Heartbeat signals the agent is still alive.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Disconnect gracefully removes an agent from the platform.
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
	// Publish sends a message to a subject.
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	// Subscribe opens a stream to receive messages on a subject.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeMessage], error)
	// Request sends a message and waits for a reply (request/reply pattern).
	Request(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*ResponseMessage, error)
	// Complete performs a blocking LLM completion.
	Complete(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (*CompletionResponse, error)
	// CompleteStream performs a streaming LLM completion.
	CompleteStream(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChunk], error)
	// ResumeStream resumes a durable stream from a given sequence.
	// Use this to reconnect after a disconnect when durable=true was used.
	ResumeStream(ctx context.Context, in *ResumeStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChunk], error)
	// ListModels returns available LLM models.
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	// CreateSession creates a new conversation session for memory.
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error)
	// GetSession retrieves an existing session.
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error)
	// DeleteSession removes a session.
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	// AddHint adds a memory hint to a session.
	AddHint(ctx context.Context, in *AddHintRequest, opts ...grpc.CallOption) (*AddHintResponse, error)
	// ListAgents returns all registered agents, optionally filtered by skill.
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	// GetAgent retrieves a specific agent by ID.
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*AgentInfo, error)
	// KVGet retrieves a value from a bucket.
	KVGet(ctx context.Context, in *KVGetRequest, opts ...grpc.CallOption) (*KVGetResponse, error)
	// KVPut stores a value in a bucket.
	KVPut(ctx context.Context, in *KVPutRequest, opts ...grpc.CallOption) (*KVPutResponse, error)
	// KVDelete removes a key from a bucket.
	KVDelete(ctx context.Context, in *KVDeleteRequest, opts ...grpc.CallOption) (*KVDeleteResponse, error)
	// KVList lists keys in a bucket with optional prefix.
	KVList(ctx context.Context, in *KVListRequest, opts ...grpc.CallOption) (*KVListResponse, error)
}

type athyrClient struct {
	cc grpc.ClientConnInterface
}

func NewAthyrClient(cc grpc.ClientConnInterface) AthyrClient {
	return &athyrClient{cc}
}

func (c *athyrClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, Athyr_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *athyrClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, Athyr_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *athyrClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, Athyr_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *athyrClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, Athyr_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *athyrClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Athyr_ServiceDesc.Streams[0], Athyr_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscribeMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Athyr_SubscribeClient = grpc.ServerStreamingClient[SubscribeMessage]

func (c *athyrClient) Request(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*ResponseMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseMessage)
	err := c.cc.Invoke(ctx, Athyr_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *athyrClient) Complete(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (*CompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompletionResponse)
	err := c.cc.Invoke(ctx, Athyr_Complete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *athyrClient) CompleteStream(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Athyr_ServiceDesc.Streams[1], Athyr_CompleteStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CompletionRequest, StreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Athyr_CompleteStreamClient = grpc.ServerStreamingClient[StreamChunk]

func (c *athyrClient) ResumeStream(ctx context.Context, in *ResumeStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Athyr_ServiceDesc.Streams[2], Athyr_ResumeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResumeStreamRequest, StreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Athyr_ResumeStreamClient = grpc.ServerStreamingClient[StreamChunk]

func (c *athyrClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, Athyr_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *athyrClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Athyr_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *athyrClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Athyr_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *athyrClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, Athyr_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *athyrClient) AddHint(ctx context.Context, in *AddHintRequest, opts ...grpc.CallOption) (*AddHintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddHintResponse)
	err := c.cc.Invoke(ctx, Athyr_AddHint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *athyrClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, Athyr_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *athyrClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*AgentInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentInfo)
	err := c.cc.Invoke(ctx, Athyr_GetAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *athyrClient) KVGet(ctx context.Context, in *KVGetRequest, opts ...grpc.CallOption) (*KVGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVGetResponse)
	err := c.cc.Invoke(ctx, Athyr_KVGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *athyrClient) KVPut(ctx context.Context, in *KVPutRequest, opts ...grpc.CallOption) (*KVPutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVPutResponse)
	err := c.cc.Invoke(ctx, Athyr_KVPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *athyrClient) KVDelete(ctx context.Context, in *KVDeleteRequest, opts ...grpc.CallOption) (*KVDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVDeleteResponse)
	err := c.cc.Invoke(ctx, Athyr_KVDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *athyrClient) KVList(ctx context.Context, in *KVListRequest, opts ...grpc.CallOption) (*KVListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVListResponse)
	err := c.cc.Invoke(ctx, Athyr_KVList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AthyrServer is the server API for Athyr service.
// All implementations must embed UnimplementedAthyrServer
// for forward compatibility.
//
// Athyr is the main platform service that agents interact with.
type AthyrServer interface {
	// Connect registers an agent with the platform.
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	// Heartbeat signals the agent is still alive.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Disconnect gracefully removes an agent from the platform.
	Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	// Publish sends a message to a subject.
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	// Subscribe opens a stream to receive messages on a subject.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeMessage]) error
	// Request sends a message and waits for a reply (request/reply pattern).
	Request(context.Context, *RequestMessage) (*ResponseMessage, error)
	// Complete performs a blocking LLM completion.
	Complete(context.Context, *CompletionRequest) (*CompletionResponse, error)
	// CompleteStream performs a streaming LLM completion.
	CompleteStream(*CompletionRequest, grpc.ServerStreamingServer[StreamChunk]) error
	// ResumeStream resumes a durable stream from a given sequence.
	// Use this to reconnect after a disconnect when durable=true was used.
	ResumeStream(*ResumeStreamRequest, grpc.ServerStreamingServer[StreamChunk]) error
	// ListModels returns available LLM models.
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	// CreateSession creates a new conversation session for memory.
	CreateSession(context.Context, *CreateSessionRequest) (*Session, error)
	// GetSession retrieves an existing session.
	GetSession(context.Context, *GetSessionRequest) (*Session, error)
	// DeleteSession removes a session.
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	// AddHint adds a memory hint to a session.
	AddHint(context.Context, *AddHintRequest) (*AddHintResponse, error)
	// ListAgents returns all registered agents, optionally filtered by skill.
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	// GetAgent retrieves a specific agent by ID.
	GetAgent(context.Context, *GetAgentRequest) (*AgentInfo, error)
	// KVGet retrieves a value from a bucket.
	KVGet(context.Context, *KVGetRequest) (*KVGetResponse, error)
	// KVPut stores a value in a bucket.
	KVPut(context.Context, *KVPutRequest) (*KVPutResponse, error)
	// KVDelete removes a key from a bucket.
	KVDelete(context.Context, *KVDeleteRequest) (*KVDeleteResponse, error)
	// KVList lists keys in a bucket with optional prefix.
	KVList(context.Context, *KVListRequest) (*KVListResponse, error)
	mustEmbedUnimplementedAthyrServer()
}

// UnimplementedAthyrServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAthyrServer struct{}

func (UnimplementedAthyrServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAthyrServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAthyrServer) Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedAthyrServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedAthyrServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeMessage]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedAthyrServer) Request(context.Context, *RequestMessage) (*ResponseMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedAthyrServer) Complete(context.Context, *CompletionRequest) (*CompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedAthyrServer) CompleteStream(*CompletionRequest, grpc.ServerStreamingServer[StreamChunk]) error {
	return status.Error(codes.Unimplemented, "method CompleteStream not implemented")
}
func (UnimplementedAthyrServer) ResumeStream(*ResumeStreamRequest, grpc.ServerStreamingServer[StreamChunk]) error {
	return status.Error(codes.Unimplemented, "method ResumeStream not implemented")
}
func (UnimplementedAthyrServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedAthyrServer) CreateSession(context.Context, *CreateSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedAthyrServer) GetSession(context.Context, *GetSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedAthyrServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedAthyrServer) AddHint(context.Context, *AddHintRequest) (*AddHintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddHint not implemented")
}
func (UnimplementedAthyrServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedAthyrServer) GetAgent(context.Context, *GetAgentRequest) (*AgentInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedAthyrServer) KVGet(context.Context, *KVGetRequest) (*KVGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KVGet not implemented")
}
func (UnimplementedAthyrServer) KVPut(context.Context, *KVPutRequest) (*KVPutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KVPut not implemented")
}
func (UnimplementedAthyrServer) KVDelete(context.Context, *KVDeleteRequest) (*KVDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KVDelete not implemented")
}
func (UnimplementedAthyrServer) KVList(context.Context, *KVListRequest) (*KVListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KVList not implemented")
}
func (UnimplementedAthyrServer) mustEmbedUnimplementedAthyrServer() {}
func (UnimplementedAthyrServer) testEmbeddedByValue()               {}

// UnsafeAthyrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AthyrServer will
// result in compilation errors.
type UnsafeAthyrServer interface {
	mustEmbedUnimplementedAthyrServer()
}

func RegisterAthyrServer(s grpc.ServiceRegistrar, srv AthyrServer) {
	// If the following call panics, it indicates UnimplementedAthyrServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Athyr_ServiceDesc, srv)
}

func _Athyr_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AthyrServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Athyr_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AthyrServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Athyr_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AthyrServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Athyr_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AthyrServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Athyr_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AthyrServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Athyr_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AthyrServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Athyr_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AthyrServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Athyr_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AthyrServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Athyr_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AthyrServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SubscribeMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Athyr_SubscribeServer = grpc.ServerStreamingServer[SubscribeMessage]

func _Athyr_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AthyrServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Athyr_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AthyrServer).Request(ctx, req.(*RequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Athyr_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AthyrServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Athyr_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AthyrServer).Complete(ctx, req.(*CompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Athyr_CompleteStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CompletionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AthyrServer).CompleteStream(m, &grpc.GenericServerStream[CompletionRequest, StreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Athyr_CompleteStreamServer = grpc.ServerStreamingServer[StreamChunk]

func _Athyr_ResumeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResumeStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AthyrServer).ResumeStream(m, &grpc.GenericServerStream[ResumeStreamRequest, StreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Athyr_ResumeStreamServer = grpc.ServerStreamingServer[StreamChunk]

func _Athyr_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AthyrServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Athyr_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AthyrServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Athyr_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AthyrServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Athyr_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AthyrServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Athyr_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AthyrServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Athyr_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AthyrServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Athyr_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AthyrServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Athyr_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AthyrServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Athyr_AddHint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AthyrServer).AddHint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Athyr_AddHint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AthyrServer).AddHint(ctx, req.(*AddHintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Athyr_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AthyrServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Athyr_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AthyrServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Athyr_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AthyrServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Athyr_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AthyrServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Athyr_KVGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AthyrServer).KVGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Athyr_KVGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AthyrServer).KVGet(ctx, req.(*KVGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Athyr_KVPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AthyrServer).KVPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Athyr_KVPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AthyrServer).KVPut(ctx, req.(*KVPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Athyr_KVDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AthyrServer).KVDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Athyr_KVDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AthyrServer).KVDelete(ctx, req.(*KVDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Athyr_KVList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AthyrServer).KVList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Athyr_KVList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AthyrServer).KVList(ctx, req.(*KVListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Athyr_ServiceDesc is the grpc.ServiceDesc for Athyr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Athyr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "athyr.v1.Athyr",
	HandlerType: (*AthyrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _Athyr_Connect_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Athyr_Heartbeat_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Athyr_Disconnect_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _Athyr_Publish_Handler,
		},
		{
			MethodName: "Request",
			Handler:    _Athyr_Request_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _Athyr_Complete_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _Athyr_ListModels_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _Athyr_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _Athyr_GetSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _Athyr_DeleteSession_Handler,
		},
		{
			MethodName: "AddHint",
			Handler:    _Athyr_AddHint_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _Athyr_ListAgents_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _Athyr_GetAgent_Handler,
		},
		{
			MethodName: "KVGet",
			Handler:    _Athyr_KVGet_Handler,
		},
		{
			MethodName: "KVPut",
			Handler:    _Athyr_KVPut_Handler,
		},
		{
			MethodName: "KVDelete",
			Handler:    _Athyr_KVDelete_Handler,
		},
		{
			MethodName: "KVList",
			Handler:    _Athyr_KVList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Athyr_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CompleteStream",
			Handler:       _Athyr_CompleteStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ResumeStream",
			Handler:       _Athyr_ResumeStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "athyr.proto",
}
