// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: athyr.proto

package athyrv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCard) Reset() {
	*x = AgentCard{}
	mi := &file_athyr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCard) ProtoMessage() {}

func (x *AgentCard) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCard.ProtoReflect.Descriptor instead.
func (*AgentCard) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{0}
}

func (x *AgentCard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentCard) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentCard) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentCard) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentCard) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentCard     *AgentCard             `protobuf:"bytes,1,opt,name=agent_card,json=agentCard,proto3" json:"agent_card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_athyr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectRequest) GetAgentCard() *AgentCard {
	if x != nil {
		return x.AgentCard
	}
	return nil
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ConnectedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_athyr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ConnectResponse) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_athyr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_athyr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_athyr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{5}
}

func (x *DisconnectRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_athyr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{6}
}

func (x *DisconnectResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_athyr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{7}
}

func (x *PublishRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PublishRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PublishRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_athyr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{8}
}

func (x *PublishResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	QueueGroup    string                 `protobuf:"bytes,3,opt,name=queue_group,json=queueGroup,proto3" json:"queue_group,omitempty"` // Optional: for load-balanced subscriptions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_athyr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SubscribeRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SubscribeRequest) GetQueueGroup() string {
	if x != nil {
		return x.QueueGroup
	}
	return ""
}

type SubscribeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Reply         string                 `protobuf:"bytes,3,opt,name=reply,proto3" json:"reply,omitempty"` // Reply subject for request/reply pattern
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeMessage) Reset() {
	*x = SubscribeMessage{}
	mi := &file_athyr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeMessage) ProtoMessage() {}

func (x *SubscribeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeMessage.ProtoReflect.Descriptor instead.
func (*SubscribeMessage) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeMessage) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SubscribeMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SubscribeMessage) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type RequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // Timeout in milliseconds (default: 5000)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMessage) Reset() {
	*x = RequestMessage{}
	mi := &file_athyr_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessage) ProtoMessage() {}

func (x *RequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessage.ProtoReflect.Descriptor instead.
func (*RequestMessage) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{11}
}

func (x *RequestMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RequestMessage) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RequestMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RequestMessage) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseMessage) Reset() {
	*x = ResponseMessage{}
	mi := &file_athyr_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMessage) ProtoMessage() {}

func (x *ResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMessage.ProtoReflect.Descriptor instead.
func (*ResponseMessage) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{12}
}

func (x *ResponseMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "system", "user", "assistant"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_athyr_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{13}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CompletionConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temperature   float64                `protobuf:"fixed64,1,opt,name=temperature,proto3" json:"temperature,omitempty"` // 0.0-1.0
	MaxTokens     int32                  `protobuf:"varint,2,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	TopP          float64                `protobuf:"fixed64,3,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`
	Stop          []string               `protobuf:"bytes,4,rep,name=stop,proto3" json:"stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionConfig) Reset() {
	*x = CompletionConfig{}
	mi := &file_athyr_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionConfig) ProtoMessage() {}

func (x *CompletionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionConfig.ProtoReflect.Descriptor instead.
func (*CompletionConfig) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{14}
}

func (x *CompletionConfig) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *CompletionConfig) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *CompletionConfig) GetTopP() float64 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *CompletionConfig) GetStop() []string {
	if x != nil {
		return x.Stop
	}
	return nil
}

type CompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*Message             `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	Config        *CompletionConfig      `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`              // Optional: for memory injection
	IncludeMemory bool                   `protobuf:"varint,6,opt,name=include_memory,json=includeMemory,proto3" json:"include_memory,omitempty"` // Whether to inject memory context
	Durable       bool                   `protobuf:"varint,7,opt,name=durable,proto3" json:"durable,omitempty"`                                  // Enable disconnect recovery for streaming
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionRequest) Reset() {
	*x = CompletionRequest{}
	mi := &file_athyr_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionRequest) ProtoMessage() {}

func (x *CompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionRequest.ProtoReflect.Descriptor instead.
func (*CompletionRequest) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{15}
}

func (x *CompletionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CompletionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompletionRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *CompletionRequest) GetConfig() *CompletionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CompletionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CompletionRequest) GetIncludeMemory() bool {
	if x != nil {
		return x.IncludeMemory
	}
	return false
}

func (x *CompletionRequest) GetDurable() bool {
	if x != nil {
		return x.Durable
	}
	return false
}

type TokenUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_athyr_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{16}
}

func (x *TokenUsage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *TokenUsage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *TokenUsage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type CompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Backend       string                 `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	Usage         *TokenUsage            `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
	FinishReason  string                 `protobuf:"bytes,5,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionResponse) Reset() {
	*x = CompletionResponse{}
	mi := &file_athyr_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionResponse) ProtoMessage() {}

func (x *CompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionResponse.ProtoReflect.Descriptor instead.
func (*CompletionResponse) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{17}
}

func (x *CompletionResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CompletionResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompletionResponse) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *CompletionResponse) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *CompletionResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *CompletionResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type StreamChunk struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Content            string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Done               bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	Usage              *TokenUsage            `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`                                                     // Only on final chunk
	Model              string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`                                                     // Only on final chunk
	Backend            string                 `protobuf:"bytes,5,opt,name=backend,proto3" json:"backend,omitempty"`                                                 // Only on final chunk
	Error              string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                                                     // Error message if failed
	AccumulatedContent string                 `protobuf:"bytes,7,opt,name=accumulated_content,json=accumulatedContent,proto3" json:"accumulated_content,omitempty"` // Content streamed before error (for retry decisions)
	PartialResponse    bool                   `protobuf:"varint,8,opt,name=partial_response,json=partialResponse,proto3" json:"partial_response,omitempty"`         // True if some content was streamed before error
	StreamInfo         *DurableStreamInfo     `protobuf:"bytes,9,opt,name=stream_info,json=streamInfo,proto3" json:"stream_info,omitempty"`                         // Only on first chunk of durable streams
	Sequence           uint64                 `protobuf:"varint,10,opt,name=sequence,proto3" json:"sequence,omitempty"`                                             // Sequence number for durable streams (for resume)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StreamChunk) Reset() {
	*x = StreamChunk{}
	mi := &file_athyr_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunk) ProtoMessage() {}

func (x *StreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunk.ProtoReflect.Descriptor instead.
func (*StreamChunk) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{18}
}

func (x *StreamChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StreamChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *StreamChunk) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *StreamChunk) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StreamChunk) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *StreamChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StreamChunk) GetAccumulatedContent() string {
	if x != nil {
		return x.AccumulatedContent
	}
	return ""
}

func (x *StreamChunk) GetPartialResponse() bool {
	if x != nil {
		return x.PartialResponse
	}
	return false
}

func (x *StreamChunk) GetStreamInfo() *DurableStreamInfo {
	if x != nil {
		return x.StreamInfo
	}
	return nil
}

func (x *StreamChunk) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// DurableStreamInfo provides connection info for subscribing to a durable stream.
// Sent as the first chunk when durable=true in the request.
type DurableStreamInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Unique identifier for this stream
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`                      // NATS subject to subscribe to for direct access
	Stream        string                 `protobuf:"bytes,3,opt,name=stream,proto3" json:"stream,omitempty"`                        // JetStream stream name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurableStreamInfo) Reset() {
	*x = DurableStreamInfo{}
	mi := &file_athyr_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurableStreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurableStreamInfo) ProtoMessage() {}

func (x *DurableStreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurableStreamInfo.ProtoReflect.Descriptor instead.
func (*DurableStreamInfo) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{19}
}

func (x *DurableStreamInfo) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DurableStreamInfo) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *DurableStreamInfo) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

// ResumeStreamRequest resumes consumption of a durable stream.
type ResumeStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`           // Stream identifier from DurableStreamInfo
	LastSequence  uint64                 `protobuf:"varint,3,opt,name=last_sequence,json=lastSequence,proto3" json:"last_sequence,omitempty"` // Last acknowledged sequence (resume from next)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeStreamRequest) Reset() {
	*x = ResumeStreamRequest{}
	mi := &file_athyr_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeStreamRequest) ProtoMessage() {}

func (x *ResumeStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeStreamRequest.ProtoReflect.Descriptor instead.
func (*ResumeStreamRequest) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{20}
}

func (x *ResumeStreamRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ResumeStreamRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResumeStreamRequest) GetLastSequence() uint64 {
	if x != nil {
		return x.LastSequence
	}
	return 0
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_athyr_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{21}
}

type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Backend       string                 `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	Available     bool                   `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_athyr_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{22}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *Model) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_athyr_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{23}
}

func (x *ListModelsResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

type SessionProfile struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Type                   string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "rolling_window"
	MaxTokens              int32                  `protobuf:"varint,2,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	SummarizationThreshold int32                  `protobuf:"varint,3,opt,name=summarization_threshold,json=summarizationThreshold,proto3" json:"summarization_threshold,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SessionProfile) Reset() {
	*x = SessionProfile{}
	mi := &file_athyr_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionProfile) ProtoMessage() {}

func (x *SessionProfile) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionProfile.ProtoReflect.Descriptor instead.
func (*SessionProfile) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{24}
}

func (x *SessionProfile) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SessionProfile) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *SessionProfile) GetSummarizationThreshold() int32 {
	if x != nil {
		return x.SummarizationThreshold
	}
	return 0
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Profile       *SessionProfile        `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_athyr_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{25}
}

func (x *CreateSessionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateSessionRequest) GetProfile() *SessionProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_athyr_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{26}
}

func (x *GetSessionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_athyr_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteSessionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DeleteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_athyr_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteSessionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SessionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Tokens        int32                  `protobuf:"varint,4,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMessage) Reset() {
	*x = SessionMessage{}
	mi := &file_athyr_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMessage) ProtoMessage() {}

func (x *SessionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMessage.ProtoReflect.Descriptor instead.
func (*SessionMessage) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{29}
}

func (x *SessionMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SessionMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SessionMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SessionMessage) GetTokens() int32 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Messages      []*SessionMessage      `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Hints         []string               `protobuf:"bytes,5,rep,name=hints,proto3" json:"hints,omitempty"`
	Profile       *SessionProfile        `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_athyr_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{30}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Session) GetMessages() []*SessionMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Session) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Session) GetHints() []string {
	if x != nil {
		return x.Hints
	}
	return nil
}

func (x *Session) GetProfile() *SessionProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type AddHintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Hint          string                 `protobuf:"bytes,3,opt,name=hint,proto3" json:"hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHintRequest) Reset() {
	*x = AddHintRequest{}
	mi := &file_athyr_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHintRequest) ProtoMessage() {}

func (x *AddHintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHintRequest.ProtoReflect.Descriptor instead.
func (*AddHintRequest) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{31}
}

func (x *AddHintRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AddHintRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddHintRequest) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

type AddHintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHintResponse) Reset() {
	*x = AddHintResponse{}
	mi := &file_athyr_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHintResponse) ProtoMessage() {}

func (x *AddHintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHintResponse.ProtoReflect.Descriptor instead.
func (*AddHintResponse) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{32}
}

func (x *AddHintResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type KVGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVGetRequest) Reset() {
	*x = KVGetRequest{}
	mi := &file_athyr_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVGetRequest) ProtoMessage() {}

func (x *KVGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVGetRequest.ProtoReflect.Descriptor instead.
func (*KVGetRequest) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{33}
}

func (x *KVGetRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *KVGetRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *KVGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KVGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVGetResponse) Reset() {
	*x = KVGetResponse{}
	mi := &file_athyr_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVGetResponse) ProtoMessage() {}

func (x *KVGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVGetResponse.ProtoReflect.Descriptor instead.
func (*KVGetResponse) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{34}
}

func (x *KVGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KVGetResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type KVPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVPutRequest) Reset() {
	*x = KVPutRequest{}
	mi := &file_athyr_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVPutRequest) ProtoMessage() {}

func (x *KVPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVPutRequest.ProtoReflect.Descriptor instead.
func (*KVPutRequest) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{35}
}

func (x *KVPutRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *KVPutRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *KVPutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVPutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type KVPutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVPutResponse) Reset() {
	*x = KVPutResponse{}
	mi := &file_athyr_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVPutResponse) ProtoMessage() {}

func (x *KVPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVPutResponse.ProtoReflect.Descriptor instead.
func (*KVPutResponse) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{36}
}

func (x *KVPutResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type KVDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVDeleteRequest) Reset() {
	*x = KVDeleteRequest{}
	mi := &file_athyr_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVDeleteRequest) ProtoMessage() {}

func (x *KVDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVDeleteRequest.ProtoReflect.Descriptor instead.
func (*KVDeleteRequest) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{37}
}

func (x *KVDeleteRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *KVDeleteRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *KVDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KVDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVDeleteResponse) Reset() {
	*x = KVDeleteResponse{}
	mi := &file_athyr_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVDeleteResponse) ProtoMessage() {}

func (x *KVDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVDeleteResponse.ProtoReflect.Descriptor instead.
func (*KVDeleteResponse) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{38}
}

func (x *KVDeleteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type KVListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"` // Optional key prefix filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVListRequest) Reset() {
	*x = KVListRequest{}
	mi := &file_athyr_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVListRequest) ProtoMessage() {}

func (x *KVListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVListRequest.ProtoReflect.Descriptor instead.
func (*KVListRequest) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{39}
}

func (x *KVListRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *KVListRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *KVListRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type KVListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVListResponse) Reset() {
	*x = KVListResponse{}
	mi := &file_athyr_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVListResponse) ProtoMessage() {}

func (x *KVListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_athyr_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVListResponse.ProtoReflect.Descriptor instead.
func (*KVListResponse) Descriptor() ([]byte, []int) {
	return file_athyr_proto_rawDescGZIP(), []int{40}
}

func (x *KVListResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_athyr_proto protoreflect.FileDescriptor

const file_athyr_proto_rawDesc = "" +
	"\n" +
	"\vathyr.proto\x12\bathyr.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xfb\x01\n" +
	"\tAgentCard\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12=\n" +
	"\bmetadata\x18\x05 \x03(\v2!.athyr.v1.AgentCard.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x0eConnectRequest\x122\n" +
	"\n" +
	"agent_card\x18\x01 \x01(\v2\x13.athyr.v1.AgentCardR\tagentCard\"k\n" +
	"\x0fConnectResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12=\n" +
	"\fconnected_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\"-\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"`\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\".\n" +
	"\x11DisconnectRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"$\n" +
	"\x12DisconnectResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"Y\n" +
	"\x0ePublishRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"!\n" +
	"\x0fPublishResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"h\n" +
	"\x10SubscribeRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1f\n" +
	"\vqueue_group\x18\x03 \x01(\tR\n" +
	"queueGroup\"V\n" +
	"\x10SubscribeMessage\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05reply\x18\x03 \x01(\tR\x05reply\"x\n" +
	"\x0eRequestMessage\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x03R\ttimeoutMs\"%\n" +
	"\x0fResponseMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"|\n" +
	"\x10CompletionConfig\x12 \n" +
	"\vtemperature\x18\x01 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x02 \x01(\x05R\tmaxTokens\x12\x13\n" +
	"\x05top_p\x18\x03 \x01(\x01R\x04topP\x12\x12\n" +
	"\x04stop\x18\x04 \x03(\tR\x04stop\"\x87\x02\n" +
	"\x11CompletionRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12-\n" +
	"\bmessages\x18\x03 \x03(\v2\x11.athyr.v1.MessageR\bmessages\x122\n" +
	"\x06config\x18\x04 \x01(\v2\x1a.athyr.v1.CompletionConfigR\x06config\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12%\n" +
	"\x0einclude_memory\x18\x06 \x01(\bR\rincludeMemory\x12\x18\n" +
	"\adurable\x18\a \x01(\bR\adurable\"\x81\x01\n" +
	"\n" +
	"TokenUsage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\"\xce\x01\n" +
	"\x12CompletionResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x18\n" +
	"\abackend\x18\x03 \x01(\tR\abackend\x12*\n" +
	"\x05usage\x18\x04 \x01(\v2\x14.athyr.v1.TokenUsageR\x05usage\x12#\n" +
	"\rfinish_reason\x18\x05 \x01(\tR\ffinishReason\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x03R\tlatencyMs\"\xe3\x02\n" +
	"\vStreamChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12*\n" +
	"\x05usage\x18\x03 \x01(\v2\x14.athyr.v1.TokenUsageR\x05usage\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x18\n" +
	"\abackend\x18\x05 \x01(\tR\abackend\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12/\n" +
	"\x13accumulated_content\x18\a \x01(\tR\x12accumulatedContent\x12)\n" +
	"\x10partial_response\x18\b \x01(\bR\x0fpartialResponse\x12<\n" +
	"\vstream_info\x18\t \x01(\v2\x1b.athyr.v1.DurableStreamInfoR\n" +
	"streamInfo\x12\x1a\n" +
	"\bsequence\x18\n" +
	" \x01(\x04R\bsequence\"d\n" +
	"\x11DurableStreamInfo\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\tR\x06stream\"t\n" +
	"\x13ResumeStreamRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12#\n" +
	"\rlast_sequence\x18\x03 \x01(\x04R\flastSequence\"\x13\n" +
	"\x11ListModelsRequest\"c\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\abackend\x18\x03 \x01(\tR\abackend\x12\x1c\n" +
	"\tavailable\x18\x04 \x01(\bR\tavailable\"=\n" +
	"\x12ListModelsResponse\x12'\n" +
	"\x06models\x18\x01 \x03(\v2\x0f.athyr.v1.ModelR\x06models\"|\n" +
	"\x0eSessionProfile\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x02 \x01(\x05R\tmaxTokens\x127\n" +
	"\x17summarization_threshold\x18\x03 \x01(\x05R\x16summarizationThreshold\"e\n" +
	"\x14CreateSessionRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x122\n" +
	"\aprofile\x18\x02 \x01(\v2\x18.athyr.v1.SessionProfileR\aprofile\"M\n" +
	"\x11GetSessionRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"P\n" +
	"\x14DeleteSessionRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"'\n" +
	"\x15DeleteSessionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x90\x01\n" +
	"\x0eSessionMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06tokens\x18\x04 \x01(\x05R\x06tokens\"\xc4\x02\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x124\n" +
	"\bmessages\x18\x03 \x03(\v2\x18.athyr.v1.SessionMessageR\bmessages\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x14\n" +
	"\x05hints\x18\x05 \x03(\tR\x05hints\x122\n" +
	"\aprofile\x18\x06 \x01(\v2\x18.athyr.v1.SessionProfileR\aprofile\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"^\n" +
	"\x0eAddHintRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04hint\x18\x03 \x01(\tR\x04hint\"!\n" +
	"\x0fAddHintResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"S\n" +
	"\fKVGetRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"A\n" +
	"\rKVGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\"i\n" +
	"\fKVPutRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\"+\n" +
	"\rKVPutResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\"V\n" +
	"\x0fKVDeleteRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"\"\n" +
	"\x10KVDeleteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"Z\n" +
	"\rKVListRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\"$\n" +
	"\x0eKVListResponse\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys2\xf3\f\n" +
	"\x05Athyr\x12V\n" +
	"\aConnect\x12\x18.athyr.v1.ConnectRequest\x1a\x19.athyr.v1.ConnectResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/connect\x12^\n" +
	"\tHeartbeat\x12\x1a.athyr.v1.HeartbeatRequest\x1a\x1b.athyr.v1.HeartbeatResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/heartbeat\x12b\n" +
	"\n" +
	"Disconnect\x12\x1b.athyr.v1.DisconnectRequest\x1a\x1c.athyr.v1.DisconnectResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/disconnect\x12V\n" +
	"\aPublish\x12\x18.athyr.v1.PublishRequest\x1a\x19.athyr.v1.PublishResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/publish\x12E\n" +
	"\tSubscribe\x12\x1a.athyr.v1.SubscribeRequest\x1a\x1a.athyr.v1.SubscribeMessage0\x01\x12V\n" +
	"\aRequest\x12\x18.athyr.v1.RequestMessage\x1a\x19.athyr.v1.ResponseMessage\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/request\x12^\n" +
	"\bComplete\x12\x1b.athyr.v1.CompletionRequest\x1a\x1c.athyr.v1.CompletionResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/complete\x12F\n" +
	"\x0eCompleteStream\x12\x1b.athyr.v1.CompletionRequest\x1a\x15.athyr.v1.StreamChunk0\x01\x12F\n" +
	"\fResumeStream\x12\x1d.athyr.v1.ResumeStreamRequest\x1a\x15.athyr.v1.StreamChunk0\x01\x12[\n" +
	"\n" +
	"ListModels\x12\x1b.athyr.v1.ListModelsRequest\x1a\x1c.athyr.v1.ListModelsResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/models\x12[\n" +
	"\rCreateSession\x12\x1e.athyr.v1.CreateSessionRequest\x1a\x11.athyr.v1.Session\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/sessions\x12_\n" +
	"\n" +
	"GetSession\x12\x1b.athyr.v1.GetSessionRequest\x1a\x11.athyr.v1.Session\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/sessions/{session_id}\x12s\n" +
	"\rDeleteSession\x12\x1e.athyr.v1.DeleteSessionRequest\x1a\x1f.athyr.v1.DeleteSessionResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/sessions/{session_id}\x12j\n" +
	"\aAddHint\x12\x18.athyr.v1.AddHintRequest\x1a\x19.athyr.v1.AddHintResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/sessions/{session_id}/hints\x12W\n" +
	"\x05KVGet\x12\x16.athyr.v1.KVGetRequest\x1a\x17.athyr.v1.KVGetResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/kv/{bucket}/{key}\x12Z\n" +
	"\x05KVPut\x12\x16.athyr.v1.KVPutRequest\x1a\x17.athyr.v1.KVPutResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/v1/kv/{bucket}/{key}\x12`\n" +
	"\bKVDelete\x12\x19.athyr.v1.KVDeleteRequest\x1a\x1a.athyr.v1.KVDeleteResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/kv/{bucket}/{key}\x12T\n" +
	"\x06KVList\x12\x17.athyr.v1.KVListRequest\x1a\x18.athyr.v1.KVListResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/kv/{bucket}B\x16Z\x14athyr/api/v1;athyrv1b\x06proto3"

var (
	file_athyr_proto_rawDescOnce sync.Once
	file_athyr_proto_rawDescData []byte
)

func file_athyr_proto_rawDescGZIP() []byte {
	file_athyr_proto_rawDescOnce.Do(func() {
		file_athyr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_athyr_proto_rawDesc), len(file_athyr_proto_rawDesc)))
	})
	return file_athyr_proto_rawDescData
}

var file_athyr_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_athyr_proto_goTypes = []any{
	(*AgentCard)(nil),             // 0: athyr.v1.AgentCard
	(*ConnectRequest)(nil),        // 1: athyr.v1.ConnectRequest
	(*ConnectResponse)(nil),       // 2: athyr.v1.ConnectResponse
	(*HeartbeatRequest)(nil),      // 3: athyr.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 4: athyr.v1.HeartbeatResponse
	(*DisconnectRequest)(nil),     // 5: athyr.v1.DisconnectRequest
	(*DisconnectResponse)(nil),    // 6: athyr.v1.DisconnectResponse
	(*PublishRequest)(nil),        // 7: athyr.v1.PublishRequest
	(*PublishResponse)(nil),       // 8: athyr.v1.PublishResponse
	(*SubscribeRequest)(nil),      // 9: athyr.v1.SubscribeRequest
	(*SubscribeMessage)(nil),      // 10: athyr.v1.SubscribeMessage
	(*RequestMessage)(nil),        // 11: athyr.v1.RequestMessage
	(*ResponseMessage)(nil),       // 12: athyr.v1.ResponseMessage
	(*Message)(nil),               // 13: athyr.v1.Message
	(*CompletionConfig)(nil),      // 14: athyr.v1.CompletionConfig
	(*CompletionRequest)(nil),     // 15: athyr.v1.CompletionRequest
	(*TokenUsage)(nil),            // 16: athyr.v1.TokenUsage
	(*CompletionResponse)(nil),    // 17: athyr.v1.CompletionResponse
	(*StreamChunk)(nil),           // 18: athyr.v1.StreamChunk
	(*DurableStreamInfo)(nil),     // 19: athyr.v1.DurableStreamInfo
	(*ResumeStreamRequest)(nil),   // 20: athyr.v1.ResumeStreamRequest
	(*ListModelsRequest)(nil),     // 21: athyr.v1.ListModelsRequest
	(*Model)(nil),                 // 22: athyr.v1.Model
	(*ListModelsResponse)(nil),    // 23: athyr.v1.ListModelsResponse
	(*SessionProfile)(nil),        // 24: athyr.v1.SessionProfile
	(*CreateSessionRequest)(nil),  // 25: athyr.v1.CreateSessionRequest
	(*GetSessionRequest)(nil),     // 26: athyr.v1.GetSessionRequest
	(*DeleteSessionRequest)(nil),  // 27: athyr.v1.DeleteSessionRequest
	(*DeleteSessionResponse)(nil), // 28: athyr.v1.DeleteSessionResponse
	(*SessionMessage)(nil),        // 29: athyr.v1.SessionMessage
	(*Session)(nil),               // 30: athyr.v1.Session
	(*AddHintRequest)(nil),        // 31: athyr.v1.AddHintRequest
	(*AddHintResponse)(nil),       // 32: athyr.v1.AddHintResponse
	(*KVGetRequest)(nil),          // 33: athyr.v1.KVGetRequest
	(*KVGetResponse)(nil),         // 34: athyr.v1.KVGetResponse
	(*KVPutRequest)(nil),          // 35: athyr.v1.KVPutRequest
	(*KVPutResponse)(nil),         // 36: athyr.v1.KVPutResponse
	(*KVDeleteRequest)(nil),       // 37: athyr.v1.KVDeleteRequest
	(*KVDeleteResponse)(nil),      // 38: athyr.v1.KVDeleteResponse
	(*KVListRequest)(nil),         // 39: athyr.v1.KVListRequest
	(*KVListResponse)(nil),        // 40: athyr.v1.KVListResponse
	nil,                           // 41: athyr.v1.AgentCard.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 42: google.protobuf.Timestamp
}
var file_athyr_proto_depIdxs = []int32{
	41, // 0: athyr.v1.AgentCard.metadata:type_name -> athyr.v1.AgentCard.MetadataEntry
	0,  // 1: athyr.v1.ConnectRequest.agent_card:type_name -> athyr.v1.AgentCard
	42, // 2: athyr.v1.ConnectResponse.connected_at:type_name -> google.protobuf.Timestamp
	42, // 3: athyr.v1.HeartbeatResponse.server_time:type_name -> google.protobuf.Timestamp
	13, // 4: athyr.v1.CompletionRequest.messages:type_name -> athyr.v1.Message
	14, // 5: athyr.v1.CompletionRequest.config:type_name -> athyr.v1.CompletionConfig
	16, // 6: athyr.v1.CompletionResponse.usage:type_name -> athyr.v1.TokenUsage
	16, // 7: athyr.v1.StreamChunk.usage:type_name -> athyr.v1.TokenUsage
	19, // 8: athyr.v1.StreamChunk.stream_info:type_name -> athyr.v1.DurableStreamInfo
	22, // 9: athyr.v1.ListModelsResponse.models:type_name -> athyr.v1.Model
	24, // 10: athyr.v1.CreateSessionRequest.profile:type_name -> athyr.v1.SessionProfile
	42, // 11: athyr.v1.SessionMessage.timestamp:type_name -> google.protobuf.Timestamp
	29, // 12: athyr.v1.Session.messages:type_name -> athyr.v1.SessionMessage
	24, // 13: athyr.v1.Session.profile:type_name -> athyr.v1.SessionProfile
	42, // 14: athyr.v1.Session.created_at:type_name -> google.protobuf.Timestamp
	42, // 15: athyr.v1.Session.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 16: athyr.v1.Athyr.Connect:input_type -> athyr.v1.ConnectRequest
	3,  // 17: athyr.v1.Athyr.Heartbeat:input_type -> athyr.v1.HeartbeatRequest
	5,  // 18: athyr.v1.Athyr.Disconnect:input_type -> athyr.v1.DisconnectRequest
	7,  // 19: athyr.v1.Athyr.Publish:input_type -> athyr.v1.PublishRequest
	9,  // 20: athyr.v1.Athyr.Subscribe:input_type -> athyr.v1.SubscribeRequest
	11, // 21: athyr.v1.Athyr.Request:input_type -> athyr.v1.RequestMessage
	15, // 22: athyr.v1.Athyr.Complete:input_type -> athyr.v1.CompletionRequest
	15, // 23: athyr.v1.Athyr.CompleteStream:input_type -> athyr.v1.CompletionRequest
	20, // 24: athyr.v1.Athyr.ResumeStream:input_type -> athyr.v1.ResumeStreamRequest
	21, // 25: athyr.v1.Athyr.ListModels:input_type -> athyr.v1.ListModelsRequest
	25, // 26: athyr.v1.Athyr.CreateSession:input_type -> athyr.v1.CreateSessionRequest
	26, // 27: athyr.v1.Athyr.GetSession:input_type -> athyr.v1.GetSessionRequest
	27, // 28: athyr.v1.Athyr.DeleteSession:input_type -> athyr.v1.DeleteSessionRequest
	31, // 29: athyr.v1.Athyr.AddHint:input_type -> athyr.v1.AddHintRequest
	33, // 30: athyr.v1.Athyr.KVGet:input_type -> athyr.v1.KVGetRequest
	35, // 31: athyr.v1.Athyr.KVPut:input_type -> athyr.v1.KVPutRequest
	37, // 32: athyr.v1.Athyr.KVDelete:input_type -> athyr.v1.KVDeleteRequest
	39, // 33: athyr.v1.Athyr.KVList:input_type -> athyr.v1.KVListRequest
	2,  // 34: athyr.v1.Athyr.Connect:output_type -> athyr.v1.ConnectResponse
	4,  // 35: athyr.v1.Athyr.Heartbeat:output_type -> athyr.v1.HeartbeatResponse
	6,  // 36: athyr.v1.Athyr.Disconnect:output_type -> athyr.v1.DisconnectResponse
	8,  // 37: athyr.v1.Athyr.Publish:output_type -> athyr.v1.PublishResponse
	10, // 38: athyr.v1.Athyr.Subscribe:output_type -> athyr.v1.SubscribeMessage
	12, // 39: athyr.v1.Athyr.Request:output_type -> athyr.v1.ResponseMessage
	17, // 40: athyr.v1.Athyr.Complete:output_type -> athyr.v1.CompletionResponse
	18, // 41: athyr.v1.Athyr.CompleteStream:output_type -> athyr.v1.StreamChunk
	18, // 42: athyr.v1.Athyr.ResumeStream:output_type -> athyr.v1.StreamChunk
	23, // 43: athyr.v1.Athyr.ListModels:output_type -> athyr.v1.ListModelsResponse
	30, // 44: athyr.v1.Athyr.CreateSession:output_type -> athyr.v1.Session
	30, // 45: athyr.v1.Athyr.GetSession:output_type -> athyr.v1.Session
	28, // 46: athyr.v1.Athyr.DeleteSession:output_type -> athyr.v1.DeleteSessionResponse
	32, // 47: athyr.v1.Athyr.AddHint:output_type -> athyr.v1.AddHintResponse
	34, // 48: athyr.v1.Athyr.KVGet:output_type -> athyr.v1.KVGetResponse
	36, // 49: athyr.v1.Athyr.KVPut:output_type -> athyr.v1.KVPutResponse
	38, // 50: athyr.v1.Athyr.KVDelete:output_type -> athyr.v1.KVDeleteResponse
	40, // 51: athyr.v1.Athyr.KVList:output_type -> athyr.v1.KVListResponse
	34, // [34:52] is the sub-list for method output_type
	16, // [16:34] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_athyr_proto_init() }
func file_athyr_proto_init() {
	if File_athyr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_athyr_proto_rawDesc), len(file_athyr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_athyr_proto_goTypes,
		DependencyIndexes: file_athyr_proto_depIdxs,
		MessageInfos:      file_athyr_proto_msgTypes,
	}.Build()
	File_athyr_proto = out.File
	file_athyr_proto_goTypes = nil
	file_athyr_proto_depIdxs = nil
}
